### ISSUE TITLE
Issues with resume/breakpoints and php adapter

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_db#11]
1. Debugger: Open
2. Debugger: Start
3. Place a breakpoint in the code
4. Reload page

Expected: Breakpoint is hit and stack trace is visible

5. Debugger: Resume
6. Reload page again

Expected: Same as after 4. Breakpoint is hit and stack trace is visible
Actual: Stack trace shows the request but doesn't expand to show file names

Here are screenshot of what happens after 4 (correct) and after 6 (incorrect).

<img width="947" alt="ok" src="https://user-images.githubusercontent.com/153197/47855095-dd01d680-dde3-11e8-8228-e8b9a56e64ad.png">
<img width="949" alt="fail" src="https://user-images.githubusercontent.com/153197/47855096-dd01d680-dde3-11e8-8bbf-d1705e9a12b4.png">

Not sure if the problem is in this package or adapter but it works fine in VSCode.

**Comment by rchl** [comment]
I can still reproduce in 0.2.4.

Only that when it fails to break the second time, the state is just as if it didn't break (but execution is still paused).

And this exception triggers when it fails to pause the second time:
```
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text/Packages/Debugger/modules/core/sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "/Users/me/Library/Application Support/Sublime Text/Packages/Debugger/modules/dap/client.py", line 328, in _on_initialized
    self._on_initialized_future.set_result(None)
  File "/Users/me/Library/Application Support/Sublime Text/Packages/Debugger/modules/libs/asyncio/futures.py", line 348, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
Debugger.modules.libs.asyncio.futures.InvalidStateError: FINISHED: <Future finished result=None>
```

**Comment by daveleroy** [comment]
Is this still an issue? If so is there a small example project that shows the issue?
