### ISSUE TITLE
Cannot start the python debugger

### ISSUE THREAD

**Issue by predragnikolic** [daveleroy/sublime_db#14]
I am on Linux.
When trying to start the python debugger. 
I get an Error:

`Error: Cannot find module '/home/predrag/.../Packages/sublime_db/debug_adapters/vscode-python/extension/out/client/debugger/MainV2.js'`

Because there is no file named `MainV2.js` in the `/debugger` folder

```
$  sublime_db/debug_adapters/vscode-python/extension/out/client/debugger ls
constants.js  debugAdapter  extension  types.js

```

____

Even though I changed this [line](https://github.com/daveleroy/sublime_db/blob/fca698363f084bb36f8b6a4afd5c2212bccabeda/debug.sublime-settings#L58) in the `debug.sublime-settings` to point to `/debugger/debugAdapter/main.js`.
```
$  sublime_db/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter ls
Common  DebugClients  DebugServers  main.js  serviceRegistry.js  types.js
```

With the following python configuration,
When starting, 
At least I see a `starting debugger...` in the Event log, 
But the debuger doesn't stop on a breaking point.

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "debug.configurations":
        [
            {
                "name": "Python (main.py)",
                "program": "${project_path}/main.py",
                "request": "launch",
                "type": "python"
            },
        ]
    }
}
```
____

Here is the log if it helps
```
running main event loop
Starting up
on_gutter_hover: 7
reloading settings Packages/User/Package Syncing.sublime-settings
new Main for window 2
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-firefox-debug/snippets.json'
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-go/snippets.json'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 594, in on_selection_modified_async
on_gutter_hover: 7
    callback.on_selection_modified_async(v)
  File "/home/predrag/.config/sublime-text-3/Packages/AutoFileName/autofilename.py", line 195, in on_selection_modified_async
    sel = view.sel()[0]
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-chrome-debug/snippets.json'
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-lldb/snippets.json'
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-chrome-debug/snippets.json'
No snippets loaded. [Errno 2] No such file or directory: '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-php/snippets.json'
Creating a window: h
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
Breakpoints: sync view  None
on_gutter_hover: 7
Package Syncing: Start Complete Sync
Package Syncing: End Complete Sync
Package Syncing: Already running
Package Control: Skipping automatic upgrade, last run at 2018-11-14 20:08:18, next run at 2018-11-14 21:08:18 or after
drag_select {'event': {'y': 93.5, 'button': 1, 'x': 194.5}}
was drag select
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
word_highlight_click {'event': {'y': 93.5, 'button': 1, 'x': 194.5}}
drag_select {'event': {'y': 93.5, 'button': 1, 'x': 194.5}, 'by': 'words'}
was drag select
on_gutter_double_clicked: 2
toggle: breakpoint <sublime_db.ui.events.GutterEvent object at 0x7efc4c30af10>
Breakpoint: toggle 3
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
Error: Failed to find breakpoint that should be set, re-adding
word_highlight_click {'event': {'y': 93.5, 'button': 1, 'x': 194.5}}
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
Breakpoints: sync view  None
Selected configuration: <sublime_db.main.configurations.Configuration object at 0x7efc4d145790>
Breakpoints: sync view  /home/predrag/Documents/sandbox/try/main.py
Error: Failed to find breakpoint that should be set, re-adding
Starting process: ['node', '/home/predrag/.config/sublime-text-3/Packages/sublime_db/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
Adapter initialize
<<  {"command": "initialize", "type": "request", "arguments": {"clientID": "sublime", "linesStartAt1": true, "columnsStartAt1": true, "adapterID": "python", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "clientName": "Sublime Text", "locale": "en-us", "supportsRunInTerminalRequest": false}, "seq": 1}
>>  {"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"supportsEvaluateForHovers":true,"supportsModulesRequest":true,"supportsValueFormattingOptions":true,"supportsHitConditionalBreakpoints":true,"supportsSetExpression":true,"supportsLogPoints":true,"supportTerminateDebuggee":true,"supportsCompletionsRequest":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
<<  {"command": "launch", "type": "request", "arguments": {"request": "launch", "type": "python", "program": "/home/predrag/Documents/sandbox/try/main.py", "name": "Python (main.py)"}, "seq": 2}
>>  {"body": {"category": "telemetry", "output": "ptvsd", "data": {"version": "4.2.0"}}, "type": "event", "event": "output", "seq": 0}
>>  {"request_seq": 2, "body": {}, "seq": 1, "success": true, "command": "launch", "message": "", "type": "response"}
Adapter has been launched/attached
<<  {"command": "threads", "type": "request", "arguments": {}, "seq": 3}
>>  {"request_seq": 1, "body": {"supportsModulesRequest": true, "supportsConfigurationDoneRequest": true, "supportTerminateDebuggee": true, "supportsEvaluateForHovers": true, "supportsSetExpression": true, "supportsExceptionOptions": true, "exceptionBreakpointFilters": [{"filter": "raised", "default": false, "label": "Raised Exceptions"}, {"filter": "uncaught", "default": true, "label": "Uncaught Exceptions"}], "supportsCompletionsRequest": true, "supportsExceptionInfoRequest": true, "supportsLogPoints": true, "supportsValueFormattingOptions": true, "supportsHitConditionalBreakpoints": true, "supportsSetVariable": true, "supportsDebuggerProperties": true, "supportsConditionalBreakpoints": true}, "seq": 2, "success": true, "command": "initialize", "message": "", "type": "response"}
An exception occured in the main_loop
Traceback (most recent call last):
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/core/core.py", line 29, in _exception_handler
    raise context['exception']
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/core/core.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/main/debug_adapter_client/client.py", line 80, in transport_message
    self.recieved_msg(msg)
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/core/core.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "/home/predrag/.config/sublime-text-3/Packages/sublime_db/main/debug_adapter_client/client.py", line 506, in recieved_msg
    future = self.pending_requests.pop(data['request_seq'])
KeyError: 1

>>  {"body": {}, "type": "event", "event": "initialized", "seq": 3}
<sublime_db.main.breakpoints.Breakpoint object at 0x7efc4c30add0> /home/predrag/Documents/sandbox/try/main.py
breakpoints: {'/home/predrag/Documents/sandbox/try/main.py': [<sublime_db.main.breakpoints.Breakpoint object at 0x7efc4c30add0>]}
<<  {"command": "setBreakpoints", "type": "request", "arguments": {"breakpoints": [{"line": 3}], "source": {"path": "/home/predrag/Documents/sandbox/try/main.py"}}, "seq": 4}
<<  {"command": "setExceptionBreakpoints", "type": "request", "arguments": {"filters": ["uncaught"]}, "seq": 5}
>>  {"body": {"reason": "started", "threadId": 1}, "type": "event", "event": "thread", "seq": 4}
<<  {"command": "threads", "type": "request", "arguments": {}, "seq": 6}
>>  {"request_seq": 3, "body": {"threads": [{"id": 1, "name": "MainThread"}]}, "seq": 5, "success": true, "command": "threads", "message": "", "type": "response"}
>>  {"request_seq": 5, "body": {}, "seq": 6, "success": true, "command": "setExceptionBreakpoints", "message": "", "type": "response"}
>>  {"request_seq": 4, "body": {"breakpoints": [{"line": 3, "verified": true, "id": 1}]}, "seq": 7, "success": true, "command": "setBreakpoints", "message": "", "type": "response"}
Configuration done!
<<  {"command": "configurationDone", "type": "request", "arguments": {}, "seq": 7}
>>  {"request_seq": 6, "body": {"threads": [{"id": 1, "name": "MainThread"}]}, "seq": 8, "success": true, "command": "threads", "message": "", "type": "response"}
>>  {"request_seq": 7, "body": {}, "seq": 9, "success": true, "command": "configurationDone", "message": "", "type": "response"}
>>  {"body": {"exitCode": 0}, "type": "event", "event": "exited", "seq": 10}
>>  {"body": {}, "type": "event", "event": "terminated", "seq": 11}
disposing Debugger
Ending process
Debugger Transport: closed
no data received, closing
LSP stdout process ended.
Breakpoints: sync view  None
```

**Comment by daveleroy** [comment]
They undoubtedly updated the location of their debug adapter. I just updated my version of the extension and changed the path. After that I was able I was able to run the example python project and it hit breakpoints just fine.

Is it working with VSCode?

**Comment by predragnikolic** [comment]
False alarm. My mistake.
I placed the breakpoint on a blank line and when I did that it never hit it.

![2018-11-14-221055_683x384_scrot](https://user-images.githubusercontent.com/22029477/48512623-3e9d5880-e85a-11e8-814a-d6006065817d.png)

**Comment by predragnikolic** [comment]
Oh well, issues are there to be solved :)

That is what I thought too, to stop on line 4.

In vs code, with the same example like in the picture above, 
When the breakpoint is on line 2 (empty line), 
The debugger executes the whole script, without stopping anywhere and it just logs `5` to the terminal. 

That is probably what happens here with your plugin, except that it doesn't log it anywhere.

**Comment by daveleroy** [comment]
I think you need to redirect the output and it should show up in the event log panel. There seems to be a lot of information about the adapter settings here https://code.visualstudio.com/docs/python/debugging

```
{
	"name": "Python Debug",
	"type": "python",
	"request": "launch",
	"program": "${project_path}/test.py",
	"debugOptions" : {
		"RedirectOutput": true,
	}
}```

Eventually I need to collect all these things and throw it in the docs since its hard to find

**Comment by predragnikolic** [comment]
And you are right. When I do that it does log 5 to `Event log`.
You really made it easy to install debuggers and to quickly get up and running. 
If I come across some issues I will report them.
