### ISSUE TITLE
Support PHP adapter 

### ISSUE THREAD

**Issue by slifin** [daveleroy/sublime_db#5]
I think this is the extension that we'd initially try and use not sure how to interface with it though
https://github.com/felixfbecker/vscode-php-debug

**Comment by daveleroy** [comment]
I just added it but didn't haven't been able to test it

**Comment by slifin** [comment]
ok, I've cloned the new version, run debugger: install adapter, seen some new files in debug_adapters, restarted sublime and then run debugger: open

I've then been prompted for a configuration which opens my project config, not really sure how to proceed in testing

**Comment by slifin** [comment]
I found the break point didn't catch, ```xdebug_break();``` in the PHP language is a function that can be called when you have xdebug installed to force a breakpoint

Screen recording:
https://www.youtube.com/watch?v=XlAuiVl2-H4&feature=youtu.be

Console output:
```
plugins loaded
plugin_loaded
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
running main event loop
Starting up
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
Package Control: Skipping automatic upgrade, last run at 2018-11-01 09:14:51, next run at 2018-11-01 10:14:51 or after
drag_select {'event': {'button': 1, 'x': 108.942871094, 'y': 202.385253906}}
drag_select {'event': {'button': 1, 'x': 188.139648438, 'y': 231.486816406}}
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
new Main for window 2
Creating a window: h
Breakpoints: sync view  /private/var/www/careplanner/test.php
Breakpoints: sync view  None
Kill Adapter
Starting process: ['node', '/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/debug_adapters/vscode-php/extension/out/phpDebug.js']
Adapter initialize
<<  {"seq": 1, "arguments": {"clientName": "Sublime Text", "supportsRunInTerminalRequest": false, "linesStartAt1": true, "supportsVariableType": true, "locale": "en-us", "pathFormat": "path", "columnsStartAt1": true, "adapterID": "python", "clientID": "sublime", "supportsVariablePaging": false}, "type": "request", "command": "initialize"}
>>  {"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":false,"supportsConditionalBreakpoints":true,"supportsFunctionBreakpoints":true,"exceptionBreakpointFilters":[{"filter":"Notice","label":"Notices"},{"filter":"Warning","label":"Warnings"},{"filter":"Error","label":"Errors"},{"filter":"Exception","label":"Exceptions"},{"filter":"*","label":"Everything","default":true}]}}
Adapter initialized: success!
<<  {"seq": 2, "arguments": {"xdebugSettings": {"max_data": 12000, "max_children": 12000, "max_depth": 12000}, "name": "xdebug", "type": "php", "request": "attach", "port": 9001}, "type": "request", "command": "attach"}
>>  {"seq":2,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Attach requests are not supported","body":{"error":{"id":0,"format":"Attach requests are not supported","showUser":true}}}
Exception in callback require_main_thread.<locals>.wrapper('{"seq":2,"ty...User":true}}}')
handle: <Handle require_main_thread.<locals>.wrapper('{"seq":2,"ty...User":true}}}')>
Traceback (most recent call last):
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/core/core.py", line 51, in wrapper
    return function(*args, **kwargs)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 81, in transport_message
    self.recieved_msg(msg)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/core/core.py", line 51, in wrapper
    return function(*args, **kwargs)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 507, in recieved_msg
    future.set_result(body)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 348, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
sublime_db.libs.asyncio.futures.InvalidStateError: FINISHED: <Future finished exception=Exception('Attach requests are not supported',)>
Future/Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/main.py", line 292, in LaunchDebugger
    yield from debugAdapterClient.Attach(adapter_config)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 290, in Attach
    yield from self.send_request_asyc('attach', config)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 494, in send_request_asyc
    value = yield from future
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 293, in result
    raise self._exception
Exception: Attach requests are not supported
no data received, closing
LSP stdout process ended.
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
Breakpoints: sync view  /private/var/www/careplanner/test.php
drag_select {'event': {'button': 1, 'x': 127.780761719, 'y': 166.701660156}}
_enter_normal_mode {'from_init': True, 'mode': 'mode_normal'}
hide_auto_complete None
Breakpoints: sync view  /private/var/www/careplanner/test.php
drag_select {'event': {'button': 1, 'x': 193.259277344, 'y': 234.267578125}}
was drag select
Disconnect Adapter
Failure writing to stdout [Errno 32] Broken pipe
Debugger Transport: closed
Kill Adapter
disposing Debugger
Ending process
OSError killing process:  [Errno 3] No such process
Kill Adapter
Starting process: ['node', '/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/debug_adapters/vscode-php/extension/out/phpDebug.js']
Adapter initialize
<<  {"seq": 1, "arguments": {"clientName": "Sublime Text", "supportsRunInTerminalRequest": false, "linesStartAt1": true, "supportsVariableType": true, "locale": "en-us", "pathFormat": "path", "columnsStartAt1": true, "adapterID": "python", "clientID": "sublime", "supportsVariablePaging": false}, "type": "request", "command": "initialize"}
>>  {"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":false,"supportsConditionalBreakpoints":true,"supportsFunctionBreakpoints":true,"exceptionBreakpointFilters":[{"filter":"Notice","label":"Notices"},{"filter":"Warning","label":"Warnings"},{"filter":"Error","label":"Errors"},{"filter":"Exception","label":"Exceptions"},{"filter":"*","label":"Everything","default":true}]}}
Adapter initialized: success!
<<  {"seq": 2, "arguments": {"xdebugSettings": {"max_data": 12000, "max_children": 12000, "max_depth": 12000}, "name": "xdebug", "type": "php", "request": "attach", "port": 9001}, "type": "request", "command": "attach"}
>>  {"seq":2,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Attach requests are not supported","body":{"error":{"id":0,"format":"Attach requests are not supported","showUser":true}}}
Exception in callback require_main_thread.<locals>.wrapper('{"seq":2,"ty...User":true}}}')
handle: <Handle require_main_thread.<locals>.wrapper('{"seq":2,"ty...User":true}}}')>
Traceback (most recent call last):
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/core/core.py", line 51, in wrapper
    return function(*args, **kwargs)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 81, in transport_message
    self.recieved_msg(msg)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/core/core.py", line 51, in wrapper
    return function(*args, **kwargs)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 507, in recieved_msg
    future.set_result(body)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 348, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
sublime_db.libs.asyncio.futures.InvalidStateError: FINISHED: <Future finished exception=Exception('Attach requests are not supported',)>
Future/Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/main.py", line 292, in LaunchDebugger
    yield from debugAdapterClient.Attach(adapter_config)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 290, in Attach
    yield from self.send_request_asyc('attach', config)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/main/debug_adapter_client/client.py", line 494, in send_request_asyc
    value = yield from future
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/sublime_db/libs/asyncio/futures.py", line 293, in result
    raise self._exception
Exception: Attach requests are not supported
no data received, closing
LSP stdout process ended.
drag_select {'event': {'button': 1, 'x': 140.041503906, 'y': 486.770019531}}
was drag select
Breakpoints: sync view  None
```

**Comment by daveleroy** [comment]
It says "Attach requests are not supported" you could try with "request" : "launch"

**Comment by daveleroy** [comment]
It looks like everything is supposed to go though the launch request for this adapter. You can see all the config here https://github.com/felixfbecker/vscode-php-debug/blob/047777b1befd3b12ebc3a7c15edcafd4af79e06c/src/phpDebug.ts#L52

```
interface LaunchRequestArguments extends VSCodeDebugProtocol.LaunchRequestArguments {
    /** The port where the adapter should listen for XDebug connections (default: 9000) */
    port?: number
    /** Automatically stop target after launch. If not specified, target does not stop. */
    stopOnEntry?: boolean
    /** The source root on the server when doing remote debugging on a different host */
    serverSourceRoot?: string
    /** The path to the source root on this machine that is the equivalent to the serverSourceRoot on the server. */
    localSourceRoot?: string
    /** The path to the source root on this machine that is the equivalent to the serverSourceRoot on the server. */
    pathMappings?: { [index: string]: string }
    /** If true, will log all communication between VS Code and the adapter to the console */
    log?: boolean
    /** Array of glob patterns that errors should be ignored from */
    ignore?: string[]
    /** XDebug configuration */
    xdebugSettings?: { [featureName: string]: string | number }

    // CLI options

    /** If set, launches the specified PHP script in CLI mode */
    program?: string
    /** Optional arguments passed to the debuggee. */
    args?: string[]
    /** Launch the debuggee in this working directory (specified as an absolute path). If omitted the debuggee is lauched in its own directory. */
    cwd?: string
    /** Absolute path to the runtime executable to be used. Default is the runtime executable on the PATH. */
    runtimeExecutable?: string
    /** Optional arguments passed to the runtime executable. */
    runtimeArgs?: string[]
    /** Optional environment variables to pass to the debuggee. The string valued properties of the 'environmentVariables' are used as key/value pairs. */
    env?: { [key: string]: string }
    /** If true launch the target in an external console. */
    externalConsole?: boolean
}
```

**Comment by slifin** [comment]
Looks like it works: 
<img width="1482" alt="screenshot 2018-11-01 at 09 56 52" src="https://user-images.githubusercontent.com/198857/47845282-8208b900-ddbc-11e8-9029-ec99c5dfca0d.png">
I couldn't get xdebug_break to catch but setting a breakpoint in the editor worked, things are buggy but as to be expected :D
